name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-action@v2
        with:
          docker-version: '20.10'
      - name: log in to Docker Hub
        # uses: docker/login-action@f045a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1
        with:
          username: muralidharansmvec@gmail.com
          password: 8124468014

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        # uses: docker/metadata-action@98669ae865ea3cffbcbaa878c20bbf1c6c38
        uses: docker/metadata-action@v3.0.0
        with:
          images: ranjithmurali98/sample_nodejs

      - name: Build and push Docker image
        # uses: docker/build-push-action@ad44023a93711e3deb337508980b5e9bcdc5dc
        uses: docker/build-push-action@v2.6.0
        with:
          content: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          

# name: Publish Node.js Project

# on:
#   push:
#     branches:
#       - 'master'

# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     container: node:16
#     steps:
#       - name: Check node version
#         run: node --version
#       - name: Check npm version
#         run: npm --version
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm install
#       - name: Node project Run
#         run: |
#           npm start &
#           PID=$!
#           sleep 1m  # Adjust the timeout as needed (e.g., 10 minutes)
#           kill $PID
