name: Publish node project

on:
  push:
    branches: ['master']
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check node version
        run: node --version
      - name: Check npm version
        run: npm --version
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: npm install
      - name: packages install
        run: npm install
      - name: run project
        run: npm start
