name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1  # Use an existing version here
        with:
          version: 21.04.0 

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_PASSWORD }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t muralidharansmvec@gmail.com/firstimage2:latest -f C:\Users\TLSPC-024\Desktop\nodejsSample\samplenodeproject\Dockerfile .
          docker push muralidharansmvec@gmail.com/firstimage2:latest


# name: Publish Node.js Project

# on:
#   push:
#     branches:
#       - 'master'

# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     container: node:16
#     steps:
#       - name: Check node version
#         run: node --version
#       - name: Check npm version
#         run: npm --version
#       - name: Check out the repo
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm install
#       - name: Node project Run
#         run: |
#           npm start &
#           PID=$!
#           sleep 1m  # Adjust the timeout as needed (e.g., 10 minutes)
#           kill $PID
