name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: log in to Docker Hub
        uses: docker/login-action@
        with:
          username:
          password:

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@
        with:
          images: thetips4you/testnodejsapp

      - name: Build and push Docker image
        uses: docker/build-push-action@
        with:
          
